create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null unique,
  description text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  collection_id bigint not null references public.collections(id) on delete restrict,
  price integer not null check (price >= 0),
  old_price integer not null default 0 check (old_price >= 0),
  rating numeric(2, 1) not null default 0 check (rating between 0 and 5),
  reviews integer not null default 0 check (reviews >= 0),
  badge text not null default '',
  stock integer not null default 0 check (stock >= 0),
  fit text not null default '',
  material text not null default '',
  care text not null default '',
  image_url text not null,
  gallery jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  description text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_gallery_is_array check (jsonb_typeof(gallery) = 'array'),
  constraint product_colors_is_array check (jsonb_typeof(colors) = 'array'),
  constraint product_sizes_is_array check (jsonb_typeof(sizes) = 'array'),
  constraint product_tags_is_array check (jsonb_typeof(tags) = 'array')
);

create index if not exists products_collection_id_idx
  on public.products(collection_id);
create index if not exists products_published_sort_idx
  on public.products(published, sort_order, created_at desc);
create index if not exists products_category_idx
  on public.products(category);

alter table public.collections enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read published collections" on public.collections;
create policy "Public can read published collections"
  on public.collections for select
  to anon, authenticated
  using (published = true);

drop policy if exists "Public can read published products" on public.products;
create policy "Public can read published products"
  on public.products for select
  to anon, authenticated
  using (published = true);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at
before update on public.collections
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();
